from EdgeLore_Language import*
from myowntestprogram import*
from Enumeration_four import*
from ListOfDirectoriesForAsunaAi import,*
from ListOfDirectoriesForAsunaAi_2 import,*
CREATE,NEW,CLASS:
      NEW,CLASS,SHALL,BE,GIVEN,NAME,"FREQUENCY.CLASSES";
            CLASS,SHALL,CONTAIN,THE,NAME,FOR,FIVE,DIFFERENT,TYPES,FOR,FREQUENCIES
            TYPE,ONE,IS,AN,"ALPHA",WAVELENGTH
            TYPE,TWO,IS,AN,"BETA",WAVELENGTH
            TYPE,THREE,IS,AN,"THETA",WAVELENGTH
            TYPE,FOUR,IS,AN,"DELTA",WAVELENGTH
            TYPE,FIVE,IS,AN,"GAMMA",WAVELENGTH
      END,CLASS:

CREATE,NEW,CLASS:
      NEW,CLASS,SHALL,BE,GIVEN,NAME,"WAVELENGTH.CLASSES";
            CLASS,SHALL,CONTAIN,THE,DATA,USED,TO,GATHER,INFORMATION,FROM,WAVELENGTH,DATA
                  DATA,SHALL,BE,GATHERED,FROM,THE,BEGINNING,LOCATION,FOR,A,WAVELENGTH
                  DATA,SHALL,BE,GATHERED,FROM,THE,DESTINATION,LOCATION,FOR,A,WAVELENGTH
                  DATA,SHALL,BE,GATHERED,FROM,THE,FREQUENCY,INFORMATION,GATHERED,FROM,WITHIN,THE,WAVELENGTH
                  #--------------------------------------------------------------------------------------------
                  DATA,SHALL,BE,GATHERED,ON,THE,NUMBER,FOR,CYCLES,A,WAVELENGTH,HAS
                  DATA,SHALL,BE,GATHERED,ON,THE,HERTZ,FOR,A,WAVELENGTH
                  DATA,SHALL,BE,GATHERED,ON,THE,LENGTH,FOR,A,WAVELENGTH
                  DATA,SHALL,BE,GATHERED,ON,THE,HEIGHT,FOR,A,WAVELENGTH
            END,CLASS:

CREATE,NEW,CLASS:
      NEW,CLASS,SHALL,BE,GIVEN,NAME,"UNIT.TYPES";
            DATA,FORMED,FROM,UNIT,TYPES,HAVE,A,SPECIFIC,FORM,FOR,INFORMATION,THAT,HAS,THE,INFORMATION,FOR,THE,UNIT,SIZE,AND,UNIT,LEVEL,FOR,THAT,SPECIFIC,UNIT,TYPE
            DATA,ANALYZED,AND,CONSIDERED,DATA,FOR,A,UNIT,TYPE,SHALL,HAVE,A,METHOD,FORMED,TO,CALCULATE,UNIT,SIZE
                  EACH,FORM,FOR,DATA,MEASURED,SHALL,HOLD,A,SPECIFIC,AMOUNT,FOR,DATA,TO,ANSWER,DATA,SIZE,LEVEL,AT,A,FUTURE,DATE
            END,COMMANDS:
      END,CLASS:
END,CLASS:
CREATE,NEW,COMMAND,PROMPT:
      SET,NEW,COMMAND,TO,GATHER,DATA,FROM,A,PARAMETER,WHEN,REQUEST,HAS,BEEN,MADE
            EACH,FORM,FOR,DATA,SHALL,BE,GIVEN,A,CATEGORY,LOCATION,TO,FORM,OUTPUT,TO,GIVING,EACH,TYPE,FOR,DATA,A,LOCATION,TO,BE,STORED,WITH,A,CATEGORY,NAME
      END,COMMAND,PROMPT:
END,COMMAND:

IF,DATA,GIVEN,A,CATEGORY,DOES,NOT,MATCH,DATA,WITH,CATEGORY:
      THEN,SCAN,OTHER,CATEGORIES,EXISTING,AND,CALCULATE,CATEGORY,WITH,SIMILAR,MATCH,TO,DATA,WITHIN,CATEGORY
      END,IF,STATEMENT:

IF,FILE,HAS,AN,EXTENSION
      THEN,ANALYZE,TYPE,FOR,FILE,EXTENSION:
      END,IF,STATEMENT:

IF,DATA,HAS,A,MEASUREMENT
      THEN,DETERMINE,CHOICE,FOR,MEASUREMENT,CLASS:
            THEN,DETERMINE,CHOICE,FOR,MEASUREMENT,CLASS,FROM,CHOICES"
            IF,CHOICE,MEASUREMENT,IS,INCHES
                  print("THE CHOICE FOR MMEASUREMEN IS INCHES");
            IF,ELSE,THEN,DETERMINE,IF,MEASUREMENT,IS,CENTIMETERS:
            IF,CHOICE,MEASUREMENT,IS,CENTIMETERS:
                  print("THE CHOICE FOR MEASUREMENT IS CENTIMETERS");
            END,IF,STATEMENTS:
      END,COMMAND:
END,IF,STATEMENT:

CREATE,CLASS,FOR,IF,STATEMENT,MANAGER,SETTINGS,FOR,MANAGING,FLOW,FOR,MEMORY,FOR,USED,IF,STATEMENT,FOR,PAST,RECALL:
      EACH,IF,STATEMENT,SHALL,BE,USED,TO,RECALL,PREVIOUS,FORMS,FOR,INFORMATION,WITHIN,DATA
      IF,EACH,FORM,FOR,IF,STATEMENT,IS,ABLE,TO,GAIN,ACCESS,TO,A,PREVIOUS,TERM
            CHECK,IF,STATEMENT,IS,A,FORM,FOR,COMMAND,AND,NOT,A,CATEGORY,REFERENCE
            IF,STATEMENT,IS,A,CATEGORY,FOR,REFERENCE
                  THEN,DISPLAY,CATEGORY
                  ELSE,DISPLAY,PREVIOUS,TERM,ACCESSED
            END,IF,STATEMENT:
      END,IF,STATEMENT:
END,COMMAND:

RECALL,DATA,WITHIN,SYSTEM,INTERFACE,FOR,COLLECTED,COORDINATE,POINTS,TO,REFERENCE,DATA,FROM
PROCESSED,REFERENCE,DATA,SHALL,BE,USED,TO,GIVE,A,CALCULATE,DATA,BY,CATEGORY,DATA,BY,POSSIBILITY,AND,CHANCE,FOR,HAPPENING,THAN,METHOD,OR,STRUCTURED,DATA
RECALL,POSSIBILITY,AS,CAN,BE,DONE,IF,POSSIBILITY,EXISTS
IF,POSSIBILITY,EXISTS,IN,MULTIPLE,FORMS,THEN,CHOOSE,THE,POSSIBILITY,WITH,BETTER,ACCURATE,EFFECTS,THAN,THE,NEUTRAL,OR,NEGATIVE,OUTCOME
MAKE,PROCESS,FOR,RECALL,PROCEDURE,TO,RECOGNIZE,COLLECTED,DATA,WITH,MANY,FORMS,FOR,TYPES,AND,CLASSES
EACH,POSSIBILITY,RECOGNIZED,MUST,BE,MADE,INTO,REFERENCE,DATA,FOR,RECALL,METHOD,TO,HAPPEN
WHEN,REFERENCE,DATA,IS,GATHERED,MAKE,POSSIBILITY,TO,GATHER,DATA,FROM,REFERENCE,SOURCE,RELATING,TO,POSITION,AND,POINT,FOR,ORIGIN,TO,OUTPUT,KNOWN,EFFECT
,
IF,SCANNER,WAS,NOT,ABLE,TO,FIND,RESULT,AT,THE,END,FOR,THE,SCANNING,PROCESS
      THEN,END,SCANNING,PROCESS
      END,COMMAND:
END,IF,STATEMENT:

IF,DATA,IS,RECOGNIZED,BY,A,CATEGORY
      THEN,DISPLAY,CATEGORY,FOR,CATEGORY,IF,ASKED,FOR,CATEGORY
      END,COMMAND:
END,IF,STATEMENT:

IF,THERE,IS,A,CLASS,WITHOUT,A,NAME
      THEN,ALLOW,TO,REQUEST,FOR,A,NAME,FOR,THE,CLASS
      END,COMMAND:
END,IF,STATEMENT:

IF,THERE,IS,A,CLASS,WITHOUT,A,TYPE
      THEN,ALLOW,TO,REQUEST,FOR,A,TYPE,FOR,THE,CLASS
      END,COMMAND:
END,IF,STATEMENT:

IF,THERE,IS,A,TYPE,WITHOUT,A,ELEMENT
      THEN,ALLOW,TO,REQUEST,FOR,A,ELEMENT,FOR,THE,TYPE
      END,COMMAND:
END,IF,STATEMENT:

IF,DATA,HAS,NO,CATEGORY
      THEN,MAKE,CATEGORY,FOR,DATA,WITH,NAME,"UNKNOWN CATEGORY"
      END,COMMAND:
END,IF,COMMAND:

MAKE,COORDINATE,PLANE
      GIVE,VALUE,TO,PLANE,TO,HAVE,LENGTH,FOR,40,INCHES
      GIVE,VALUE,TO,PLANE,TO,HAVE,WIDTH,FOR,40,INCHES
      END,COMMAND:
END,COMMAND:






DEFAULT,PROGRAM,USED,TO,USE,AN,['__EXTENSIONTYPE__'],FILE,IS,"__PROGRAMNAME__"
#DEFAULT,PROGRAM,USED,TO,USE,AN,['.MP4'],FILE,IS,"VLC_PLAYER"
#DEFAULT,PROGRAM,USED,TO,USE,AN,['.TXT'],FILE,IS,"NOTEPADPLUSPLUS"
#DEFAULT,PROGRAM,USED,TO,USE,AN,['.DOCX'],FILE,IS,"MICROSFORT_WORD"
#DEFAULT,PROGRAM,USED,TO,USE,AN,['.MP3'],FILE,IS,"VLC_PLAYER"
#DEFAULT,PROGRAM,USED,TO,USE,AN,['.PY'],FILE,IS,"VS_CODE"
#DEFAULT,PROGRAM,USED,TO,USE,AN,['.JSON'],FILE,IS,"VS_CODE"

['__EXTENSIONTYPE__'],IS,A,FILE,EXTENSION:
#['.MP4'],IS,A,FILE,EXTENSION
#['.TXT'],IS,A,FILE,EXTENSION
#['.DOCX'],IS,A,FILE,EXTENSION
#['.MP3'],IS,A,FILE,EXTENSION
#['.PY'],IS,A,FILE,EXTENSION
#['.JSON'],IS,A,FILE,EXTENSION
#['.LNK'],IS,A,FILE,EXTENSION
#['.EXE'],IS,A,FILE,EXTENSION

("__FOLDER_PATH__"),IS,A,FOLDER,LOCATION:
#("C:\ASUNAAI"),IS,A,FOLDER,LOCATION
#("C:\ASUNAAI\EXTENSIONS"),IS,A,FOLDER,LOCATION

("__FOLDER_PATH__"),IS,A,FOLDER,DIRECTORY:
#("C:\ASUNAAI"),IS,A,FOLDER,DIRECTORY
#("C:\ASUNAAI\EXTENSIONS"),IS,A,FOLDER,DIRECTORY

("__FOLDER_PATH__"),IS,A,FOLDER,PATH:
#("C:\ASUNAAI"),IS,A,FOLDER,PATH
#("C:\ASUNAAI\EXTENSIONS"),IS,A,FOLDER,PATH

["__FILENAME__"],IS,A,FILE:
#["MPBR_Frequency"],IS,A,FILE
#["Language_Early_Stage"],IS,A,FILE

["__FILENAME__"],IS,A,['__EXTENSIONTYPE__'],FILE:
#["MPBR_Frequency"],IS,A,['.TXT'],FILE
#["Language_Early_Stage"],IS,A,['.PY'],FILE

["__FILENAME__"],IS,LOCATED,WITHIN,("__FOLDER_PATH__"):
#["MPBR_Frequency"],IS,LOCATED,WITHIN,("C:\ASUNAAI\EXTENSIONS\TXT")
#["Language_Early_Stage"],IS,LOCATED,WITHIN,("C:\ASUNAAI\EXTENSIONS\PY")

LOCATE,FILE,WITH,NAME,["__FILENAME__"],WITHIN,FOLDER,DIRECTORY,("__FOLDER_PATH__");
#LOCATE,FILE,WITH,NAME,["MPBR_Frequency"],WITHIN,FOLDER,DIRECTORY,("C:\ASUNAAI\EXTENSIONS\TXT")

SCAN,FOLDER,DIRECTORY,("__FOLDER_PATH__"),FOR,FILE,WITH,NAME,["__FILENAME__"];
#SCAN,FOLDER,DIRECTORY,("C:\ASUNAAI\EXTENSIONS\PY"),FOR,FILE,WITH,NAME,["Language_Early_Stage"]

ANALYZE,FOLDER,DIRECTORY,("__FOLDER_PATH__"),FOR,["__FILENAME__"];
#ANALYZE,FOLDER,DIRECTORY,("C:\ASUNAAI\EXTENSIONS\TXT"),FOR,["MPBR_Frequency"]

CHANGE,FOLDER,DIRECTORY,TO,("__FOLDER_PATH__");
#CHANGE,FOLDER,DIRECTORY,TO,("C:\ASUNAAI\EXTENSIONS\MP3")

LIST,ALL,FOLDER,LOCATIONS,WITHIN,("__FOLDER_PATH__");
#LIST,ALL,FOLDER,LOCATIONS,WITHIN,("C:\ASUNAAI\EXTENSIONS\PY")


SCAN,SYSTEM,AND,LOCATE,FILE,WITH,NAME,["__FILENAME__"],AND,OUTPUT,FOLDER,DIRECTORY
#SCAN,SYSTEM,AND,LOCATE,FILE,WITH,NAME,("MPBR_FREQUENCY.TXT"),AND,OUTPUT,FOLDER,DIRECTORY

SCAN,SYSTEM,AND,LOCATE,FOLDER,WITH,NAME,("__FOLDER_NAME__"),AND,OUTPUT,DIRECTORY,LOCATION
#SCAN,SYSTEM,AND,LOCATE,FOLDER,WITH,NAME,("EXTENSIONS"),AND,OUTPUT,DIRECTORY,LOCATION

SCAN,FOR,AND,GO,TO,DIRECTORY,("__FOLDER_PATH__")
#SCAN,FOR,AND,GO,TO,DIRECTORY,("C:/ASUNAAI/ASUNAAIEXTENSIONS/DOCX")

OPEN,["__FILENAME__"],WITHIN,FILE,DIRECTORY,("__FOLDER_PATH__")
#OPEN,["EDGELOREDOCUMENTS.DOCX"],WITHIN,FILE,DIRECTORY,("C:/ASUNAAI/ASUNAAIEXTENSIONS/DOCX")

OPEN,["__FILENAME__"],WITHIN,FILE,DIRECTORY,("__FOLDER_PATH__")
#OPEN,"CHROME.LNK",WITHIN,FILE,DIRECTORY,("C:/ASUNAAI/ASUNAAIEXTENSIONS/LNK")

START,["__FILENAME__"],WITHIN,FILE,DIRECTORY,("__FOLDER_PATH__")
#START,["VLC_PLAYER.LNK"],WITHIN,FILE,DIRECTORY,("C:/ASUNAAI/ASUNAAIEXTENSIONS/LNK")

LOCATE,FILE,WITH,NAME,["__FILENAME__"],WITHIN,FILE,DIRECTORY,("__FOLDER_PATH__"),AND,OPEN,["__FILENAME__"]
#LOCATE,FILE,WITH,NAME,["EDGELOREDOCUMENTS.DOCX"],WITHIN,FILE,DIRECTORY,("C:/ASUNAAI"),AND,OPEN,["EDGELOREDOCUMENTS.DOCX"]

CREATE,NEW,FILE,INSIDE,FOLDER,DIRECTORY,("__FOLDER_PATH__"),AND,NAME,THE,FILE,["__FILENAME__"]
#CREATE,NEW,FILE,INSIDE,FOLDER,DIRECTORY,("C:/ASUNAAI/ASUNAAIEXTENSIONS/TXT"),AND,NAME,THE,FILE,["HELLO,WORLD.TXT"]

CREATE,NEW,FOLDER,INSIDE,FOLDER,DIRECTORY,("__FOLDER_PATH__"),WITH,NAME,FOR,FILE,GIVEN,["__FILENAME__"]
#CREATE,NEW,FOLDER,INSIDE,FOLDER,DIRECTORY,("C:/ASUNAAI/ASUNAAIEXTENSIONS"),WITH,NAME,FOR,FILE,GIVEN,"SEVENZIP"

GO,TO,FILE,DIRECTORY,("__FOLDER_PATH__")
#GO,TO,FILE,DIRECTORY,("C:/ASUNAAI/ASUNAAIEXTENSIONS")

LOCATE,ALL,FILES,WITHIN,FOLDER,DIRECTORY,("__FOLDER_PATH__"),WITH,NAME,["__FILENAME__"]
#LOCATE,ALL,FILES,WITHIN,FOLDER,DIRECTORY,("C:/ASUNAAI/"),WITH,NAME,["EDGELOREDOCUMENTS"]

CHANGE,FILE,DIRECTORY,TO,LOCATION,("__FOLDER_PATH__")
#CHANGE,FILE,DIRECTORY,TO,LOCATION,("C:/ASUNAAI/ASUNAAIEXTENSIONS")

ACTIVATE,["__FILENAME__"]
#ACTIVATE,"VSCODE.LNK"

MAKE,A,SQUARE,WITH,A,LENGTH,FOR,5,AND,WIDTH,FOR,5

MAKE,A,SQUARE,PERIMETER,WITH,LENGTH,FOR,36,AND,WIDTH,FOR,36

MAKE,A,DIMENSION,WITH,LENGTH,FOR,12



WHAT,IS,THE,CURRENT,FILE,DIRECTORY
OUTPUT:,("C:/ASUNAAI/ASUNAAIEXTENSIONS/MP4")


WHAT,IS,MY,DEFAULT,FILE,DIRECTORY
OUTPUT:,("C:/ASUNAAI")

WHAT,IS,{4,+,4}
OUTPUT,8

WHAT,IS,{12,*,12}
OUTPUT,144

WHAT,IS,{8*2+2(12*2)}
OUTPUT,64

WHAT,IS,THE,AREA,FOR,A,SQUARE,IF,THE,LENGTH,IS,5
OUTPUT,25



WHAT,IS,THE,DIAMETER,FOR,A,CIRCLE,WITH,A,RADIUS,FOR,6
OUTPUT,12

MAKE,OPTION,TO,ALLOW,RECALLING,WORDS,USED:
MAKE,OPTION,TO,ALLOW,READING,A,DOCUMENT:
MAKE,OPTION,TO,ALLOW,SCANNING,PARTICLE,DATA:
MAKE,OPTION,TO,ALLOW,SCANNING,FREQUENCY,DATA:
MAKE,OPTION,TO,MEASURE,A,DIMENSIONAL,LENGTH,USING,INCHES:
MAKE,OPTION,TO,LEARN,DATA,GIVEN,TO,READ,BY,HEADADMINZACK:
MAKE,OPTION,TO,READ,EMOTIONAL,RESPONSES:

A,WORD,IS,MADE,WITH,MORE,THAN,ONE,LETTER:
A,BOOK,CONSISTS,WITH,MORE,THAN,ONE,WORD:
A,SCRIPT,CONSISTS,WITH,MORE,THAN,ONE,WORD:
A,LIBRARY,CAN,HOLD,MANY,FORMS,WITH,SPECIFIC,KNOWLEDGE:

CREATE,CALIBRATION,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,FREQUENCY,DATA
CREATE,MEASUREMENT,SYSTEM,THAT,SHALL,BE,USED,TO,MEASURE,DATA
CREATE,FREQUENCY,SYSTEM,THAT,SHALL,BE,USED,TO,GATHER,DATA,FROM,LEARNED,FREQUENCY,PATTERNS:

CREATE,OPTION,TO,FORM,PARAGRAPHS,WITH,WORDS:
CREATE,OPTION,TO,FORM,A,PARAGRAPH,WITH,WORDS:
CREATE,OPTION,TO,RECOGNIZE,DATA,CLASS:
CREATE,OPTION,TO,RECALL,DATA,FROM,OTHER,DATA:
CREATE,OPTION,TO,RECOGNIZE,A,EXTENSION,TYPE,FOR,FILE,DATA:
CREATE,OPTION,TO,RECOGNIZE,FREQUENCY,DATA,FROM,PATTERN,RESPONSE,DATA

CREATE,CLASS
GIVE,NAME,TO,CLASS,CREATED,AS,""

CREATE,NEW,SCREEN,RESOLUTION
SCREEN,RESOLUTION,LENGTH,IS,CONSIDERED,120,PIXELS,PER,INCH
SCREEN,RESOLUTION,LENGTH,IS,CONSIDERED,120,PIXELS,PER,INCH

["_CREATURENAME_"],HAS,A,ATTACKSTAT,OF,80

["_CREATURENAME_"],HAS,A,DEFENSESTAT,OF,70

["_CREATURENAME_"],HAS,A,SPECIALDEFENSESTAT,OF,90

["_CREATURENAME_"],HAS,A,SPECIALATTACKSTAT,OF,70

["_CREATURENAME_"],HAS,A,SPEEDSTAT,OF,110

["_CREATURENAME_"],HAS,THE,ABILITY,["_ABILITYNAME_"]

THE,TECHNIQUE,["_MOVENAME_"],EXISTS,WITHIN,["_CREATURENAME_"],LIST,OF,KNOWN,TECHNIQUES

["_MOVENAME_"],SHALL,ACTIVATE,A,"SANDSTORM",FOR,TWO,MINUTES

APPROVE,THE,TECHNIQUE,["_MOVENAME_"],EXISTS,WITHIN,["_CREATURENAME_"],LIST,OF,KNOWN,TECHNIQUES,POSSIBILITY,OBTAIN,TECHNIQUE,["_MOVENAME_"],UPON,AT2,LEVEL,5

["_CREATURENAME_"],CAN,BE,FOUND,WITH,LEVELS,BETWEEN,LEVEL,2,TO,LEVEL,5

ROUTE,211,HAS,A,.20,CHANCE,TO,FIND,["_CREATURENAME_"],INSIDE,SHORTGRASS,DURING,DAYTIME,WHILE,THE,"SEASON",IS,SPRING

THE,HIGHEST,LEVEL,["_CREATURENAME_"],CAN,REACH,IS,LEVEL,100

THE,LOWEST,LEVEL,["_CREATURENAME_"],CAN,REACH,IS,LEVEL,1

THE,BASEATTACK,OF,["_CREATURENAME_"],IS,120

THE,DEFAULT,ACCURACYSTAT,OF,["_CREATURENAME_"],IS,.99

THE,ATTACKSTAT,OF,["_CREATURENAME_"],IS,[],AT,LEVEL,50

MAKE,LIST,FOR,DATA
      LIST,CONTAINS,THE,FOLLOWING,DATA,["HEALTH_POINTS","MAGIC_POINTS","MANA_BAR"]
            DEFINE,HEALTH_POINTS,AS,['THE NUMBER FOR HEALTH POINTS A PLAYER HAS']
            THE,NUMBER,FOR,HEALTH_POINTS,IS,100
            END,COMMANDS:
            DEFINE,MAGIC_POINTS,AS,['THE AMOUNT FOR MAGIC POINTS A PLAYER HAS']
            THE,NUMBER,FOR,MAGIC_POINTS,IS,40
            END,COMMANDS:
            DEFINE,MANA_BAR,AS,['THE SIZE FOR MANA GIVEN AS A SPECIFIC AMOUNT MADE INTO A BAR FOR MANA']
            SET,MANA_BAR,SIZE,TO,CONTAIN,120,MANA,AT,MOST
            SET,MANA_BAR,SIZE,TO,CONTAIN,10,MANA,AS,MIN,AMOUNT
            END,COMMANDS:
      END,LIST:
END,COMMAND:

POWER,FOR,LENGTH,[_SETPOWERFORLENGTHHERE_]:
POWER,FOR,WIDTH,[_SETPOWERFORWIDTHHERE_]:
POWER,FOR,HEIGHT,[_SETPOWERFORWIDTHHERE_]:

LEVEL,FOR,PERIMETER,[_SETLEVELFORPERIMETERHERE_]:
LEVEL,FOR,AREA,[_SETLEVELFORAREAHERE_]
